Remove unmaintained tempdir library
Cargill/cylinder pull request #61
Opened 2022-02-25 18:19 UTC by leebradley

Remove unmaintained tempdir library in favor of tempfile:3.3

See: https://rustsec.org/advisories/RUSTSEC-2018-0017

Signed-off-by: Lee Bradley <bradley@bitwise.io>

2022-02-25 18:38 UTC, peterschwarz approved these changes, later dismissed

2022-02-25 19:44 UTC, peterschwarz approved these changes, later dismissed

2022-07-19 15:32 UTC, vaporos requested changes

2022-07-19 15:32 UTC, vaporos commented on libcylinder/src/key/load.rs
> +        let temp_dir = TempDir::new().expect("Failed to create temp dir");
In order to retain the prefix, this should be Builder::new()::prefix("test_key_dir").tempdir().expect("Failed to create temp dir"); (with a use tempfile::Builder above).

2022-07-19 16:10 UTC, peterschwarz submitted a review, later dismissed

2022-07-19 16:34 UTC, peterschwarz submitted a review, later dismissed

2022-07-20 15:32 UTC, vaporos approved these changes

2022-07-20 15:41 UTC, peterschwarz approved these changes

2022-07-20 15:41 UTC, merged